### PR TITLE
feat: add forwardRef to TransitionLink

### PR DESCRIPTION
**Pull request by kevsimpson**
Based on reach router implementation: https://github.com/reach/router/blob/master/src/index.js#L368

https://github.com/TylerBarnes/gatsby-plugin-transition-link/issues/98#issue-453645748

### CODE REVIEW

**Comment by TylerBarnes** [comment]
Hey @kevsimpson , thanks for this!

I tried it out and forwardRef wasn't working for me. I removed it and used the innerRef prop you had added instead and that seems to work great.

Maybe I'm missing something, let me know if you know why it wasn't working.

I tried 
```
          <AniLink fade ref={this.fadeRef} to="/page-2">
            Go to page 2 with a fade
          </AniLink>
```

And I just got an error about using refs on a functional component and that I should use React.forwardRef. Since you already had it set up that way I found that a bit confusing.

**Comment by kevsimpson** [comment]
Hey @TylerBarnes, not a problem :) 

The PR only implements `forwardRef` on the `TransitionLink` component itself.
Hence why you're getting the error about refs on functional components.

So basically, if you wanted to use refs with `AniLink` too, `forwardRef` has to be implemented on `AniLink` along with its dependency components such as `Fade`.

**Comment by TylerBarnes** [comment]
Life gets crazy sometimes! Apologies for waiting on this for so long and thanks again. What you did works perfectly.

**Comment by crutchcorn** [comment]
Can we get a version of this published to `npm`? It seems like this was merged but never released to `npm` as a stable release

**Comment by TylerBarnes** [comment]
D'oh! 🤦‍♀️it's available in `gatsby-plugin-transition-link@1.13.0`

**Pull request merged**
