### PR TITLE
Property to configure swipe offset

### PR DESCRIPTION
**Pull request by jacekk**
Proposed change set allows to configure bottom layer **offset** while using **swipe** animation in **AniLink**. Setting this value to `100` looks like a regular slider (when new slide pushes away the old one) which looks way better in my case.

Hopefully, this might be useful not only for me :)

### CODE REVIEW

**Comment by TylerBarnes** [comment]
Hey @jacekk thanks for this, I like it!
I added a couple small commits and changed the prop name from `swipeBottomOffset` to `entryOffset`. Here is the reason (copy pasted from my second commit message).

The name change is for two reasons:
1. design: I like to try to keep the anilink props as succinct as possible. The don't need to be namespaced to a specific animation as other animations should ignore the prop if it isn't supported.
2. clarification: on the swipe animation there is a prop called "top" that allows you to determine wether the entering page is on the top or bottom. So the offset may apply to either the top or bottom layer but will always apply to the entering page.

**Comment by TylerBarnes** [comment]
Thanks for contributing and apologies for the delay on this!
I've been really wanting to put more time into my open source stuff but I've just been slammed with work + life stuff lately. 
Thanks again!

**Comment by jacekk** [comment]
@TylerBarnes Works great after your improvements. Thx :)

One question, shouldn't the following page be updated: https://transitionlink.tylerbarnes.ca/docs/anilink/ ?? Otherwise, no one will know/use this tiny feature :/

**Comment by TylerBarnes** [comment]
Good point! I've added it to that page.
Thanks again

**Pull request merged**
