### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by deioo**
* add featurist.co.uk site

### CODE REVIEW

**Comment by deioo** [comment]
@TylerBarnes any tips on how to get this in please? I'm missing something pretty obvious I'm sure :)

**Comment by luchoster** [comment]
@deioo did you see this? https://app.codacy.com/app/tylerdbarnes/gatsby-plugin-transition-link/pullRequest?prid=3857004

**Comment by deioo** [comment]
Hi @luchoster, yes, I did. Was confused about the PR format, as I looked at other PRs and they looks the same to me.
Also that code warning is all over the readme. I did use GitHub’s GUI to edit the file, but that doesn’t seem to be the problem?
Thanks for your help!

**Comment by TylerBarnes** [comment]
Thanks @deioo, your site looks great!
I'll need to go through the repo and do some cleanup anyway so don't worry about the warning.

Thanks again!

**Comment by TylerBarnes** [comment]
Also thanks @luchoster for chiming in! The help is appreciated

**Pull request merged**
